#!/usr/bin/env python3
"""Generate a German (QWERTZ) labeled keymap-drawer config from the base config.

The base media/keymap-config.yaml renders the layout with US-QWERTY symbol
labels. This script produces media/keymap-config-de.yaml which overrides the
displayed symbols to the German QWERTZ keyboard positions (Y<->Z, umlauts,
and the German punctuation row), WITHOUT touching the actual ZMK keymap.

Usage:  python3 media/generate_de_config.py
Output: media/keymap-config-de.yaml
"""
import copy
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML missing: pip install pyyaml")

base = Path(__file__).parent / "keymap-config.yaml"
out = Path(__file__).parent / "keymap-config-de.yaml"

cfg = yaml.safe_load(base.read_text())

# German QWERTZ symbol overrides applied on top of the base zmk_keycode_map.
# (tap / shifted) following the standard German layout.
GERMAN = {
    # Y/Z swap (QWERTZ). Base renders letters uppercase; tap = lowercase z/y.
    "Y": {"t": "z", "s": "Z"},
    "Z": {"t": "y", "s": "Y"},
    # Number row shifted symbols (German).
    "N2": {"t": "2", "s": '"'},
    "NUMBER_2": {"t": "2", "s": '"'},
    "N3": {"t": "3", "s": "\u00a7"},
    "NUMBER_3": {"t": "3", "s": "\u00a7"},
    "N4": {"t": "4", "s": "$"},
    "NUMBER_4": {"t": "4", "s": "$"},
    "N5": {"t": "5", "s": "%"},
    "NUMBER_5": {"t": "5", "s": "%"},
    "N6": {"t": "6", "s": "&"},
    "NUMBER_6": {"t": "6", "s": "&"},
    "N7": {"t": "7", "s": "/"},
    "NUMBER_7": {"t": "7", "s": "/"},
    "N8": {"t": "8", "s": "("},
    "NUMBER_8": {"t": "8", "s": "("},
    "N9": {"t": "9", "s": ")"},
    "NUMBER_9": {"t": "9", "s": ")"},
    "N0": {"t": "0", "s": "="},
    "NUMBER_0": {"t": "0", "s": "="},
    # Punctuation / symbol row (German positions).
    "MINUS": {"t": "\u00df", "s": "?"},
    "EQUAL": {"t": "\u00b4", "s": "`"},
    "LEFT_BRACKET": {"t": "\u00fc", "s": "\u00dc"},
    "LBKT": {"t": "\u00fc", "s": "\u00dc"},
    "RIGHT_BRACKET": {"t": "+", "s": "*"},
    "RBKT": {"t": "+", "s": "*"},
    "BACKSLASH": {"t": "#", "s": "'"},
    "BSLH": {"t": "#", "s": "'"},
    "SEMICOLON": {"t": "\u00f6", "s": "\u00d6"},
    "SEMI": {"t": "\u00f6", "s": "\u00d6"},
    "SINGLE_QUOTE": {"t": "\u00e4", "s": "\u00c4"},
    "SQT": {"t": "\u00e4", "s": "\u00c4"},
    "COMMA": {"t": ",", "s": ";"},
    "PERIOD": {"t": ".", "s": ":"},
    "DOT": {"t": ".", "s": ":"},
    "SLASH": {"t": "-", "s": "_"},
    "FSLH": {"t": "-", "s": "_"},
    # Slot where the US backquote lives -> German ' (akut) key.
    "GRAVE": {"t": "\u00b4", "s": "`"},
}

# Existing base symbol aliases that were strings / other forms.
keymap_section = cfg.get("parse_config", {}).get("zmk_keycode_map", {})
# Apply overrides; normalise "NUMBER_X" aliases already present.
for key, val in GERMAN.items():
    keymap_section[key] = val

out.write_text(
    "# Generated by generate_de_config.py from keymap-config.yaml.\n"
    + "\n# German (QWERTZ) symbol labels for layout images. The ZMK keymap itself\n"
    "# is unchanged; only the rendered symbols are remapped to the German layout.\n"
    + yaml.safe_dump(cfg, allow_unicode=True, sort_keys=False)
)
print(f"Wrote {out}")
